### ISSUE TITLE
salt cmd.run segmentation fault on Centos7 VM

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/devstack-formula#13]
Getting consistent Salt segfault on Cent7 when running `devstack` formula.
```
          ID: openstack-devstack configure local_conf and run stack
    Function: cmd.run
        Name: /opt/opensds-linux-amd64-devstack/stack.sh
      Result: False
     Comment: Command "/opt/opensds-linux-amd64-devstack/stack.sh" run
     Started: 14:20:15.905394
    Duration: 139683.212 ms
     Changes:   
              ----------
              pid:
                  31267
              retcode:
                  1
```
Note: Salt can have "segmentation fault" when OS has not enough compute resources.  This looks different as works on Ubuntu.
